apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-project
  namespace: staging
spec:
  rules:
    - host: staging.the-project.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-project
                port:
                  number: 3000

