apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: the-project

patchesJson6902:
- path: broadcaster-env-patch.json
  target:
    group: apps
    kind: Deployment
    name: broadcaster
    version: v1

# Remove postgres-backup cronjob for staging
patchesStrategicMerge:
- remove-postgres-backup.yaml

images:
- name: akiracry/broadcaster
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/broadcaster
  newTag: 3427978cede0bc65c8e4ddd768bc0b818fd9fc44
- name: akiracry/the-project
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/the-project
  newTag: 3427978cede0bc65c8e4ddd768bc0b818fd9fc44
- name: akiracry/todo-backend
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/todo-backend
  newTag: 3427978cede0bc65c8e4ddd768bc0b818fd9fc44
