apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-analysis
  namespace: exercises
spec:
  metrics:
    - name: cpu-usage-rate
      interval: 30s
      count: 10
      successCondition: result[0] <= 2.0
      failureCondition: result[0] > 2.0
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.prometheus:9090
          query: |
            sum(
              rate(container_cpu_usage_seconds_total{namespace="exercises", container!="POD", container!=""}[1m])
            )

