apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

