apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: akiracry/the-project:2.6
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: IMAGE_URL
            - name: CACHE_DURATION
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: CACHE_DURATION
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: TODO_BACKEND_URL
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
      volumes:
        - name: cache-volume
          emptyDir: {}

