apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - todo-backend-configmap.yaml
  - todo-backend-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-backup-cronjob.yaml

