apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: the-project

images:
  - name: akiracry/the-project
    newName: akiracry/the-project
    newTag: latest
  - name: akiracry/todo-backend
    newName: akiracry/todo-backend
    newTag: latest
  - name: akiracry/broadcaster
    newName: akiracry/broadcaster
    newTag: latest

