apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- ../../base

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: the-project

images:
- name: akiracry/broadcaster
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/broadcaster
  newTag: 3166fa87aa895df8397eb993a1ab0bdef4dc3bf5
- name: akiracry/the-project
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/the-project
  newTag: 3166fa87aa895df8397eb993a1ab0bdef4dc3bf5
- name: akiracry/todo-backend
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/todo-backend
  newTag: 3166fa87aa895df8397eb993a1ab0bdef4dc3bf5
- name: postgres-backup
  newName: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/postgres-backup
  newTag: 3166fa87aa895df8397eb993a1ab0bdef4dc3bf5
