apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-generator
  namespace: project
spec:
  schedule: "0 * * * *"  # Every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  # Get random Wikipedia article URL
                  WIKI_URL=$(curl -s -L -o /dev/null -w '%{url_effective}' https://en.wikipedia.org/wiki/Special:Random)
                  
                  # Create todo via todo-backend API
                  curl -X POST http://todo-backend:3000/api/todos \
                    -H "Content-Type: application/json" \
                    -d "{\"text\": \"Read $WIKI_URL\"}"
                  
                  echo "Created todo: Read $WIKI_URL"
          restartPolicy: OnFailure

