apiVersion: v1
kind: Service
metadata:
  name: wikipedia-app
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: wikipedia-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

