apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output
  namespace: exercises
spec:
  rules:
    - host: log-output.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-output
                port:
                  number: 3000
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong
                port:
                  number: 3000

