apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller
      containers:
        - name: controller
          image: europe-north1-docker.pkg.dev/dotted-byway-481522-f5/docker-repo/dummysite-controller:latest
          env:
            - name: PORT
              value: "3000"
          resources:
            limits:
              cpu: 200m
              memory: 128Mi

