apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: akiracry/the-project:2.4
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
      volumes:
        - name: cache-volume
          emptyDir: {}

